apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spring-application.fullname" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "spring-application.fullname" . }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spring-application.fullname" . }}-role