name: App Deployment

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - pom.xml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - pom.xml
      - '*.yaml'

env:
  CONTAINER_REGISTRY_NAME: gmezanregistry001
  RELEASE_NAME: spring-app
  AKS_RESOURCE_GROUP: rg-terraform-gh-actions-01
  AKS_NAME: cluster-selected-hookworm

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Verify with Maven
        run: mvn --batch-mode --update-snapshots clean install
  ci:
    name: Continuous integration
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v4
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            CONTAINER_IMAGE_NAME=$(echo $RELEASE_NAME)
            echo container image: $CONTAINER_IMAGE_NAME, acr: $CONTAINER_REGISTRY_NAME
            az acr build \
              --registry "$CONTAINER_REGISTRY_NAME" \
              --image "$CONTAINER_IMAGE_NAME" \
              --file Dockerfile . \
              --platform linux
  cd:
    name: Continuous Delivery
    #if: github.ref == 'refs/heads/main'
    environment: sandbox
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_NAME }}
      - uses: azure/k8s-bake@v3
        id: bake
        with:
          renderEngine: 'helm'
          releaseName: ${{ env.RELEASE_NAME }}
          namespace: default
          helmChart: ./chart
          overrideFiles: './azure.yaml'
          overrides: |
            image.repository: ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.RELEASE_NAME }}
          helm-version: 'latest'
          silent: 'false'
      - uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: default